# Generated by Django 3.2.4 on 2021-07-16 09:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 7, 16, 9, 50, 47, 331436), editable=False),
        ),
    ]
